# Generated by Django 5.2 on 2025-06-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaMonumento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monumento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='monumentos/'),
        ),
    ]
